resolver: lts-22.20
packages:
- 'Base'
- 'Backend-blashs'
- 'Backend-blashs/Example/MNIST'
- 'Backend-blashs/Example/imdb'
#- 'Backend-hmatrix'
#- 'Backend-hmatrix/Example/MNIST'
extra-deps:
- blas-hs-0.1.1.0
# - hmatrix-0.18.0.0
- tokenize-0.3.0
flags:
  blas-hs:
    openblas: true
  neural-network-blashs:
    vec128: true
  hmatrix:
    openblas: true

extra-package-dbs: []

arch: x86_64
extra-include-dirs: []
extra-lib-dirs: []
ghc-options:
    "$locals": -O3 -rtsopts
